name: DbApp

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Tests
        shell: bash 
        run: |
              cd ./MVCApp
              dotnet test

      - name: Build for win-x64
        shell: bash 
        run: |
              cd ./MVCApp
              dotnet publish -c Release -r win-x64 --self-contained

      - name: Build for linux-x64
        shell: bash 
        run: |
              cd ./MVCApp
              dotnet publish -c Release -r linux-x64 --self-contained